inventory:
  options:
    defaults_file: Inventory/defaults.yaml
    group_file: Inventory/groups.yaml
    host_file: Inventory/hosts_LG.yaml
  plugin: SimpleInventory
options:
  num_workers: 5
runner:
  plugin: serial
ssh:
  config_file: ssh_config
