inventory:
  options:
    defaults_file: Inventory/defaults.yaml
    group_file: Inventory/groups.yaml
    host_file: /Users/hdinnobl/venv/AUVA/network_automation/Inventory/hosts_US.yaml
  plugin: SimpleInventory
options:
  num_workers: 5
runner:
  plugin: serial
ssh:
  config_file: ssh_config
