#SWUM0001:
#  hostname: 10.208.79.39
#  platform: ios
#  port: 22
SWUM11159:
  hostname: 10.208.111.59
  platform: ios
  port: 22
SWUMEGVH11:
  hostname: 10.208.111.46
  platform: ios
  port: 22
SWUMEGVH12:
  hostname: 10.208.111.25
  platform: ios
  port: 22
SWUMEGVH13:
  hostname: 10.208.111.54
  platform: ios
  port: 22
SWUMEGVH21:
  hostname: 10.208.111.22
  platform: ios
  port: 22
SWUMEGVH22:
  hostname: 10.208.111.21
  platform: ios
  port: 22
SWUMEGVH31:
  hostname: 10.208.111.47
  platform: ios
  port: 22
SWUMEGVH32:
  hostname: 10.208.111.53
  platform: ios
  port: 22
SWUMKGVH11:
  hostname: 10.208.111.45
  platform: ios
  port: 22
SWUMKGVH12:
  hostname: 10.208.111.52
  platform: ios
  port: 22
SWUMKGVH21:
  hostname: 10.208.111.48
  platform: ios
  port: 22
SWUMKGVH22:
  hostname: 10.208.111.49
  platform: ios
  port: 22
SWUMOG1VH11:
  hostname: 10.208.111.39
  platform: ios
  port: 22
SWUMOG1VH12:
  hostname: 10.208.111.36
  platform: ios
  port: 22
SWUMOG1VH13:
  hostname: 10.208.111.38
  platform: ios
  port: 22
SWUMOG1VH14:
  hostname: 10.208.111.42
  platform: ios
  port: 22
SWUMOG1VH15:
  hostname: 10.208.111.44
  platform: ios
  port: 22
SWUMOG1VH16:
  hostname: 10.208.111.57
  platform: ios
  port: 22
SWUMOG1VH21:
  hostname: 10.208.111.37
  platform: ios
  port: 22
SWUMOG1VH22:
  hostname: 10.208.111.41
  platform: ios
  port: 22
SWUMOG1VH31:
  hostname: 10.208.111.20
  platform: ios
  port: 22
SWUMOG1VH41:
  hostname: 10.208.111.33
  platform: ios
  port: 22
SWUMOG1VH42:
  hostname: 10.208.111.32
  platform: ios
  port: 22
SWUMOG1VH43:
  hostname: 10.208.111.31
  platform: ios
  port: 22
SWUMOG1VH44:
  hostname: 10.208.111.58
  platform: ios
  port: 22
SWUMOG2VH11:
  hostname: 10.208.111.26
  platform: ios
  port: 22
SWUMOG2VH12:
  hostname: 10.208.111.34
  platform: ios
  port: 22
SWUMOG3VH11:
  hostname: 10.208.111.27
  platform: ios
  port: 22
SWUMOG3VN11:
  hostname: 10.208.111.28
  platform: ios
  port: 22
SWUMOG4VH11:
  hostname: 10.208.111.29
  platform: ios
  port: 22
SWUMOG4VN12:
  hostname: 10.208.111.43
  platform: ios
  port: 22
SWUMOG5VH11:
  hostname: 10.208.111.23
  platform: ios
  port: 22
SWUMOG5VN11:
  hostname: 10.208.111.24
  platform: ios
  port: 22
SWUMZK1VH11:
  hostname: 10.208.111.55
  platform: ios
  port: 22
SWUMZKUVH11:
  hostname: 10.208.111.56
  platform: ios
  port: 22
