at-vie-an-sw1.bmaa.local:
  hostname: 172.25.2.253
  platform: ios
  port: 22
at-vie-bka-verm.bmaa.local:
  hostname: 172.20.254.12
  platform: ios
  port: 22
at-vie-bka-voice-sw.bmaa.local:
  hostname: 172.20.254.10
  platform: ios
  port: 22
at-vie-fa-sw1.bmaa.local:
  hostname: 172.25.4.253
  platform: ios
  port: 22
at-vie-log-sw1.bmaa.local:
  hostname: 172.20.254.16
  platform: ios
  port: 22
at-vie-log-sw2.bmaa.local:
  hostname: 172.20.254.17
  platform: ios
  port: 22
at-vie-log-sw3.bmaa.local:
  hostname: 172.20.254.101
  platform: ios
  port: 22
at-vie-nag-sw01.bmaa.local:
  hostname: 172.20.254.14
  platform: ios
  port: 22
at-vie-sw10008.bmaa.local:
  hostname: 172.20.254.20
  platform: ios
  port: 22
at-vie-sw11012.bmaa.local:
  hostname: 172.20.254.21
  platform: ios
  port: 22
at-vie-sw11026.bmaa.local:
  hostname: 172.20.254.22
  platform: ios
  port: 22
at-vie-sw11044-1.bmaa.local:
  hostname: 172.20.254.43
  platform: ios
  port: 22
at-vie-sw12012.bmaa.local:
  hostname: 172.20.254.23
  platform: ios
  port: 22
at-vie-sw12048-0.bmaa.local:
  hostname: 172.20.254.46
  platform: ios
  port: 22
at-vie-sw12048-2.bmaa.local:
  hostname: 172.20.254.45
  platform: ios
  port: 22
at-vie-sw13012.bmaa.local:
  hostname: 172.20.254.25
  platform: ios
  port: 22
at-vie-sw13025-1.bmaa.local:
  hostname: 172.20.254.220
  platform: ios
  port: 22
at-vie-sw13025.bmaa.local:
  hostname: 172.20.254.26
  platform: ios
  port: 22
at-vie-sw13050.bmaa.local:
  hostname: 172.20.254.27
  platform: ios
  port: 22
at-vie-sw14017.bmaa.local:
  hostname: 172.20.254.28
  platform: ios
  port: 22
at-vie-sw14030.bmaa.local:
  hostname: 172.20.254.29
  platform: ios
  port: 22
at-vie-sw22019.bmaa.local:
  hostname: 172.20.254.30
  platform: ios
  port: 22
at-vie-sw22054.bmaa.local:
  hostname: 172.20.254.31
  platform: ios
  port: 22
at-vie-sw22067.bmaa.local:
  hostname: 172.20.254.32
  platform: ios
  port: 22
at-vie-sw23018.bmaa.local:
  hostname: 172.20.254.33
  platform: ios
  port: 22
at-vie-sw23057.bmaa.local:
  hostname: 172.20.254.34
  platform: ios
  port: 22
at-vie-sw23070.bmaa.local:
  hostname: 172.20.254.35
  platform: ios
  port: 22
at-vie-sw24023.bmaa.local:
  hostname: 172.20.254.36
  platform: ios
  port: 22
at-vie-sw24061.bmaa.local:
  hostname: 172.20.254.37
  platform: ios
  port: 22
at-vie-sw24075.bmaa.local:
  hostname: 172.20.254.38
  platform: ios
  port: 22
at-vie-sw25026.bmaa.local:
  hostname: 172.20.254.39
  platform: ios
  port: 22
at-vie-sw25061.bmaa.local:
  hostname: 172.20.254.119
  platform: ios
  port: 22
at-vie-sw25065.bmaa.local:
  hostname: 172.20.254.117
  platform: ios
  port: 22
at-vie-sw25079-1.bmaa.local:
  hostname: 172.20.254.41
  platform: ios
  port: 22
at-vie-sw25079-2.bmaa.local:
  hostname: 172.20.254.42
  platform: ios
  port: 22
at-vie-sw30056.bmaa.local:
  hostname: 172.20.254.50
  platform: ios
  port: 22
at-vie-sw32100.bmaa.local:
  hostname: 172.20.254.51
  platform: ios
  port: 22
at-vie-tv-sw1.bmaa.local:
  hostname: 172.25.99.216
  platform: ios
  port: 22
at-vie-vid-sw1.bmaa.local:
  hostname: 172.20.254.15
  platform: ios
  port: 22
