SWRMEGVB1:
  hostname: 10.208.111.16
  platform: ios
  port: 22
SWRMEGVG1:
  hostname: 10.208.111.14
  platform: ios
  port: 22
SWRMEGVR1:
  hostname: 10.208.111.15
  platform: ios
  port: 22
SWRMEGVTH1:
  hostname: 10.208.111.19
  platform: ios
  port: 22
SWRMEGVTH2:
  hostname: 10.208.111.17
  platform: ios
  port: 22
SWRMIGVTH1:
  hostname: 10.208.111.8
  platform: ios
  port: 22
SWRMOG1VB1:
  hostname: 10.208.111.9
  platform: ios
  port: 22
SWRMOG1VG1:
  hostname: 10.208.111.10
  platform: ios
  port: 22
SWRMOG1VG2:
  hostname: 10.208.111.7
  platform: ios
  port: 22
SWRMOG1VR1:
  hostname: 10.208.111.11
  platform: ios
  port: 22
SWRMOG1VTH1:
  hostname: 10.208.111.50
  platform: ios
  port: 22
SWRMOG1VTH2:
  hostname: 10.208.111.5
  platform: ios
  port: 22
SWRMOG2VTH1:
  hostname: 10.208.111.51
  platform: ios
  port: 22
SWRMOG2VTH2:
  hostname: 10.208.111.6
  platform: ios
  port: 22
SWRMUG1VTH1:
  hostname: 10.208.111.18
  platform: ios
  port: 22
SWRMUGVG1:
  hostname: 10.208.111.12
  platform: ios
  port: 22
SWRMUGVR1:
  hostname: 10.208.111.13
  platform: ios
  port: 22
